name: BID
channels:
- pytorch
- defaults
dependencies:
- python=3.7.7
- pytorch=1.7.1
- torchvision=0.8.2
- scipy
- pip:
  - dominate==2.4.0
  - Pillow==6.1.0
  - numpy==1.16.4
  - visdom==0.1.8
  - packaging
  - GPUtil==1.4.0
  - opencv-python ==3.4.2.17
